import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

const envPath = path.resolve('.env');
const token = crypto.randomBytes(32).toString('base64url');
const current = await readExistingEnv();
const values = new Map();

for (const line of current.split('\n')) {
  const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
  if (match) values.set(match[1], match[2]);
}

if (!isStrongToken(values.get('REMOTE_TOKEN'))) {
  values.set('REMOTE_TOKEN', token);
}

values.set('PORT', values.get('PORT') || '8787');
values.set('HOST', values.get('HOST') || '0.0.0.0');
values.set('CODEX_COMMAND', values.get('CODEX_COMMAND') || 'codex');
values.set('CODEX_WORKDIR', values.get('CODEX_WORKDIR') || process.cwd());
values.set('CODEX_PROJECT_ROOTS', values.get('CODEX_PROJECT_ROOTS') || path.dirname(process.cwd()));
values.set('TRUST_PROXY', values.get('TRUST_PROXY') || 'false');
values.set('PUBLIC_URL', values.get('PUBLIC_URL') || '');

const nextEnv = [
  '# Generated by `npm run setup`.',
  '# Keep this file private. It contains the token that unlocks Codex Relay.',
  `REMOTE_TOKEN=${values.get('REMOTE_TOKEN')}`,
  '',
  '# Local app-server',
  `PORT=${values.get('PORT')}`,
  `HOST=${values.get('HOST')}`,
  `CODEX_COMMAND=${values.get('CODEX_COMMAND')}`,
  `CODEX_WORKDIR=${values.get('CODEX_WORKDIR')}`,
  `CODEX_PROJECT_ROOTS=${values.get('CODEX_PROJECT_ROOTS')}`,
  '',
  '# Use true only when the server is behind your trusted HTTPS tunnel or reverse proxy.',
  `TRUST_PROXY=${values.get('TRUST_PROXY')}`,
  '',
  '# Optional HTTPS tunnel URL for phone setup.',
  `PUBLIC_URL=${values.get('PUBLIC_URL')}`,
  ''
].join('\n');

await fs.writeFile(envPath, nextEnv, { mode: 0o600 });

const localIp = getLocalIp();
const port = values.get('PORT');

console.log('Codex Relay setup is ready.');
console.log(`Local URL: http://${localIp || 'localhost'}:${port}`);
console.log(`Token: ${values.get('REMOTE_TOKEN')}`);
console.log('');
console.log('Next: npm start');

async function readExistingEnv() {
  try {
    return await fs.readFile(envPath, 'utf8');
  } catch {
    return '';
  }
}

function isStrongToken(value = '') {
  const weak = new Set(['change-me', 'change-me-to-a-long-random-token', 'password', 'token', 'secret']);
  return value.length >= 32 && !weak.has(value.trim().toLowerCase());
}

function getLocalIp() {
  for (const addresses of Object.values(os.networkInterfaces())) {
    for (const address of addresses || []) {
      if (address.family === 'IPv4' && !address.internal) {
        return address.address;
      }
    }
  }
  return '';
}
